### ISSUE TITLE
 pyenv is awesome but...

### ISSUE THREAD

**Issue by lifeBalance** [yyuu/pyenv-virtualenvwrapper#25]
Is there a way of not having to issue the command ``$ pyenv virtualenvwrapper`` every time I want to start working with my environments?
I have been a long time user of **virtualenv** and **virtualenvwrapper**, where it wasn't neccessary to do that, just ``workon`` to list environments and start working.

**Comment by blueyed** [comment]
I recommend using https://github.com/yyuu/pyenv-virtualenv instead.

And then you can use your virtualenvs like normal pyenv versions, e.g. setting it for a project's dir using `pyenv local venv-foo`.

If you want to also auto-activate the virtualenvs, then add `pyenv virtualenv init -` to your shell config, or use something like https://github.com/Tarrasch/zsh-autoenv to call `pyenv activate` automatically.

(Apart from that, `workon` also only works because you init it in your shell config, where you could also add `pyenv virtualenvwrapper(_lazy)`, but it slows down startup.)

**Comment by lifeBalance** [comment]
Thanks for your answer Daniel, but I'm very used to **virtualenvwrapper** and plain **virtualenv** is not gonna make it for me. Anyways, I'll keep an eye open on **pyenv**, until that feature get a bit more polished.

**Comment by blueyed** [comment]
@lifeBalance 
As said, you are probably only missing the call to `pyenv virtualenvwrapper` in your shell config.

Using pyenv-virtualenv would be an enhancement over virtualenvwrapper, which is not really necessary with pyenv, where pyenv itself allows to control and activate the different virtualenvs easily.

E.g., instead of `workon foo` you would do `pyenv shell foo`, or `pyenv local foo` to make it permanent for some dir and it's subdirs.
With `pyenv local foo` it would then get activated automatically when you enter the project dir even.

Anyway, closing this issue, since it's not really a bug/issue with with pyenv-virtualenvwrapper anyway.

**Comment by lifeBalance** [comment]
To many anyways... Anyway, I don't think **virtualenv/pyenv-virtualenv** would be an enhancement over **virtualenvwrapper/pyenv-virtualenvwrapper**,  just the opposite. If I have to take a wild guess, I'd say you haven't use **virtualenvwrapper** much, if you want, you can check the documentation [here](http://virtualenvwrapper.readthedocs.org/en/latest/) to see all its features. In any case, there are a lot of people using it because it's a great tool. Even projects like [virtualenv-burrito](https://github.com/brainsik/virtualenv-burrito) with more than 500 stars, are built on  top of **virtualenv + virtualenvwrapper**.
Anyways, thanks for the info about adding ``pyenv virtualenvwrapper`` to my shell configuration, maybe not being present in the **README** was my issue ;)

**Comment by blueyed** [comment]
Feel free to submit a PR for the README.  You're right that it does not explicitly state adding it to your shell startup file, but that has the drawback of being slow.  Therefore virtualenvwrapper-lazy exists, but it's still slow (see e.g. https://github.com/yyuu/pyenv-virtualenvwrapper/issues/13 where it got improved).

I've started myself using virtualenvwrapper, then discovered pyenv and used pyenv-virtualenvwrapper, but ditched it in the meantime.

pyenv-virtualenvwrapper provides an interface to virtualenvwrapper, but pyenv-virtualenv makes virtualenvs first-class pyenv Python versions.  See also https://github.com/yyuu/pyenv-virtualenvwrapper/pull/18 (and the follow-ups).

**Comment by yyuu** [comment]
Because pyenv and virtualenvwrapper have distincted semantics for version management, it's pretty hard to make them cooperate. I started writing this project to make it as a bridge of both two, but it is not well matured compared to pyenv-virtualenv at least for now. Pull Requests are welcome since we still need to improve much more, eapecially for documentation since I am pretty bad at documentation ;)

**Comment by lifeBalance** [comment]
Yes, I can imagine it must be difficult. Maybe it would have been easier bringing a simpler idea like **chruby** to python, that's what I use when I do ruby, I couldn't care less about shims(rbenv), for me switching rubies is enough, and I prefer not to share gems between rubies. Oh man, **chruby + virtual environments** sounds so good, think about it ))

**Comment by mikenerone** [comment]
I was with virtualenvwrapper for many years. We kept a strong relationship through all the ups and downs life threw at us. We found different ways to maintain that spark we had, often just sharing our affection, sometimes spicing things up to keep it fresh. I thought we'd be together forever. But then I met pyenv-virtualenv. What can I say? Sometimes you just can't help falling in love. Don't judge me.

Seriously, pyenv-virtualenv is better in nearly every way. I _did_ need to add [direnv](http://direnv.net/) into the mix to replace the functionality of `postactivate` (which I found I only really used for env vars), but then it turned out that I liked direnv even better for this purpose anyway. I _do_ miss are some of the helper commands (`workon`, `cdsitepackages`, etc.) a little from time to time, but those would be easy enough to implement with some simple shell functions. I should sit down for ten minutes and do that. But meh.
